### ISSUE TITLE
Add links to our communication channels like Slack and Meetup

### ISSUE THREAD

**Issue by gnublet** [CodeForTucson/new-cft-website-deprecated-#3]
Add the slack, meetup, and any other helpful links (like social media) to the README.md markdown to make navigation and communication more seemless for newcomers.

- Slack: codefortucson.slack.com
- Meetup: https://www.meetup.com/Code-for-Tucson/

Feel free to place this wherever on the README.md that makes the most sense to you.

**Comment by yslDevelop** [comment]
do you mind If i take this issue? will do asap

**Comment by gnublet** [comment]
@yslDevelop not at all!

**Comment by gnublet** [comment]
If you are not yet added as a collaborator, you may first need to fork the repo. After you push your changes to your forked repo, you can submit a pull request for it to be merged into this one.

**Comment by gnublet** [comment]
If you're still working on this, someone submitted a pull request which was merged. However, it could still be improved by removing the query parameter in the meetup link and adding additional social media links (I don't have the links, but you can reach out in the Slack group to find them)

**Comment by yslDevelop** [comment]
I was swamped by other works this and last week.
I'm so sorry for the late response :(

**Comment by gnublet** [comment]
No need to apologize, take your time! There aren't any timelines for open source projects like these. Plus, the "good first issue" issues are more to help you learn
